name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    if: github.repository == 'adam-coquelet/vue-avatar-gradient'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check Git version
        run: git --version

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN_AUTOMATION}}" > .npmrc

      - name: Publish package
        run: npm publish
